[package]
name = "rs_adc_bluepill"
version = "0.1.0"
edition = "2024"

[dependencies]
rs_bluepill = { path = "../rs_bluepill" }
rs_gpio_bluepill = { path = "../rs_gpio_bluepill" }
rs_rcu_bluepill = { path = "../rs_rcu_bluepill" }
rs_timer_bluepill = { path = "../rs_timer_bluepill" }
rs_dma_bluepill = { path = "../rs_dma_bluepill" }
