#![allow(dead_code)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.72.1 */

pub type lnPin = cty::c_int;

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum lnGpioMode {
    lnFLOATING = 0,
    lnINPUT_FLOATING = 1,
    lnINPUT_PULLUP = 2,
    lnINPUT_PULLDOWN = 3,
    lnOUTPUT = 4,
    lnOUTPUT_OPEN_DRAIN = 5,
    lnALTERNATE_PP = 6,
    lnALTERNATE_OD = 7,
    lnPWM = 8,
    lnADC_MODE = 9,
    lnDAC_MODE = 10,
    lnUART = 11,
    lnSPI_MODE = 12,
    lnUART_Alt = 13,
}
pub const LnRemapTimer_NoRemap: LnRemapTimer = 0;
pub const LnRemapTimer_PartialRemap: LnRemapTimer = 1;
pub const LnRemapTimer_FullRemap: LnRemapTimer = 3;
pub type LnRemapTimer = cty::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lnFastIO {
    pub _onoff: *mut cty::c_uint,
    pub _onbit: cty::c_uint,
    pub _offbit: cty::c_uint,
    pub _in: *mut cty::c_uint,
    pub _inbit: cty::c_uint,
}
impl lnFastIO {
    #[inline]
    pub unsafe fn new(p: lnPin) -> Self {
        let mut __bindgen_tmp = ::core::mem::MaybeUninit::uninit();
        lnFastIO_lnFastIO(__bindgen_tmp.as_mut_ptr(), p);
        __bindgen_tmp.assume_init()
    }
}
unsafe extern "C" {
    #[link_name = "\u{1}_Z9lnPinMode5lnPin10lnGpioModej"]
    pub fn lnPinMode(pin: lnPin, mode: lnGpioMode, speedInMhz: cty::c_uint);
    #[link_name = "\u{1}_Z14lnDigitalWrite5lnPinb"]
    pub fn lnDigitalWrite(pin: lnPin, value: bool);
    #[link_name = "\u{1}_Z13lnDigitalRead5lnPin"]
    pub fn lnDigitalRead(pin: lnPin) -> bool;
    #[link_name = "\u{1}_Z15lnDigitalToggle5lnPin"]
    pub fn lnDigitalToggle(pin: lnPin);
    #[link_name = "\u{1}_Z16lnOpenDrainClose5lnPinb"]
    pub fn lnOpenDrainClose(pin: lnPin, close: bool);
    #[link_name = "\u{1}_Z23lnGetGpioToggleRegisterj"]
    pub fn lnGetGpioToggleRegister(port: cty::c_uint) -> *mut cty::c_uint;
    #[link_name = "\u{1}_Z26lnGetGpioDirectionRegisterj"]
    pub fn lnGetGpioDirectionRegister(port: cty::c_uint) -> *mut cty::c_uint;
    #[link_name = "\u{1}_Z22lnGetGpioValueRegisterj"]
    pub fn lnGetGpioValueRegister(port: cty::c_uint) -> *mut cty::c_uint;
    #[link_name = "\u{1}_Z10lnReadPortj"]
    pub fn lnReadPort(port: cty::c_uint) -> cty::c_uint;
    #[link_name = "\u{1}_Z15lnRemapTimerPinj12LnRemapTimer"]
    pub fn lnRemapTimerPin(timer: cty::c_uint, map: LnRemapTimer);
    #[link_name = "\u{1}_ZN8lnFastIOC1E5lnPin"]
    pub fn lnFastIO_lnFastIO(this: *mut lnFastIO, p: lnPin);
    pub fn lnGetGpioOnRegister(port: cty::c_uint) -> *mut cty::c_uint;
    pub fn lnGetGpioOffRegister(port: cty::c_uint) -> *mut cty::c_uint;
    pub fn lnPinMode_c(pin: lnPin, mode: lnGpioMode, speedInMhz: cty::c_uint);
}
