[package]
name = "rust_demo"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rp2040 = []

[dependencies]
cty = "0.2.2"
rust_esprit = { path = "../../esprit/rust/rust_esprit"}
ufmt = "*"

[lib]
name = "rust_demo"
path = "src/lib.rs"
crate-type = ["staticlib"] # Creates static lib

[profile.dev]
debug = true
lto = false
opt-level       = 0

[profile.release]
debug = true
lto = true
opt-level       = 0
