//! Raw C‑language bindings for the Esprit hardware abstraction layer.
//!
//! All modules are auto‑generated by `bindgen` (see `c_interface/bindgen.sh`)
//! and provide unsafe FFI declarations to the underlying C/C++ HAL.
//! They are re‑exported from the crate root for backward compatibility.
//!
//! You should not normally need to use these modules directly; prefer the
//! safe wrappers in `crate::gpio`, `crate::task`, `crate::sync`, etc.

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#[cfg(feature = "cdc")]
pub mod rn_cdc_c;
pub mod rn_debug_c;
pub mod rn_exti_c;
pub mod rn_fast_event_c;
pub mod rn_freertos_c;
#[cfg(not(any(feature = "rp2040", feature = "esp32")))]
pub mod rn_gpio_bp_c;
#[cfg(feature = "esp32")]
pub mod rn_gpio_esp32_c;
#[cfg(feature = "rp2040")]
pub mod rn_gpio_rp2040_c;
pub mod rn_i2c_c;
pub mod rn_spi_c;
pub mod rn_timer_c;
pub mod rn_timing_adc_c;
pub mod rn_serial_c;
#[cfg(feature = "cdc")]
pub mod rn_usb_c;
