#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const __SSP_FORTIFY_LEVEL: u32 = 0;
pub const __int20: u32 = 2;
pub const __int20__: u32 = 2;
pub type __int8_t = cty::c_schar;
pub type __uint8_t = cty::c_uchar;
pub type __int16_t = cty::c_short;
pub type __uint16_t = cty::c_ushort;
pub type __int32_t = cty::c_int;
pub type __uint32_t = cty::c_uint;
pub type __int64_t = cty::c_longlong;
pub type __uint64_t = cty::c_ulonglong;
pub type __int_least8_t = cty::c_schar;
pub type __uint_least8_t = cty::c_uchar;
pub type __int_least16_t = cty::c_short;
pub type __uint_least16_t = cty::c_ushort;
pub type __int_least32_t = cty::c_int;
pub type __uint_least32_t = cty::c_uint;
pub type __int_least64_t = cty::c_longlong;
pub type __uint_least64_t = cty::c_ulonglong;
pub type __intmax_t = cty::c_longlong;
pub type __uintmax_t = cty::c_ulonglong;
pub type __intptr_t = cty::c_int;
pub type __uintptr_t = cty::c_uint;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type int_least8_t = __int_least8_t;
pub type uint_least8_t = __uint_least8_t;
pub type int_least16_t = __int_least16_t;
pub type uint_least16_t = __uint_least16_t;
pub type int_least32_t = __int_least32_t;
pub type uint_least32_t = __uint_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = cty::c_schar;
pub type uint_fast8_t = cty::c_uchar;
pub type int_fast16_t = cty::c_short;
pub type uint_fast16_t = cty::c_ushort;
pub type int_fast32_t = cty::c_int;
pub type uint_fast32_t = cty::c_uint;
pub type int_fast64_t = cty::c_longlong;
pub type uint_fast64_t = cty::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ln_i2c_c {
    pub dummy: *mut cty::c_void,
}
unsafe extern "C" {
    pub fn lni2c_create(instance: cty::c_uint, speed: cty::c_uint) -> *mut ln_i2c_c;
}
unsafe extern "C" {
    pub fn lni2c_delete(i2c: *mut ln_i2c_c);
}
unsafe extern "C" {
    pub fn lni2c_setSpeed(ptr: *mut ln_i2c_c, speed: cty::c_uint);
}
unsafe extern "C" {
    pub fn lni2c_setAddress(ptr: *mut ln_i2c_c, address: cty::c_uint);
}
unsafe extern "C" {
    pub fn lni2c_write(ptr: *mut ln_i2c_c, n: cty::c_uint, data: *const u8) -> bool;
}
unsafe extern "C" {
    pub fn lni2c_read(ptr: *mut ln_i2c_c, n: cty::c_uint, data: *mut u8) -> bool;
}
unsafe extern "C" {
    pub fn lni2c_write_to(
        ptr: *mut ln_i2c_c,
        target: cty::c_uint,
        n: cty::c_uint,
        data: *const u8,
    ) -> bool;
}
unsafe extern "C" {
    pub fn lni2c_multi_write_to(
        ptr: *mut ln_i2c_c,
        target: cty::c_uint,
        nbSeqn: cty::c_uint,
        seqLength: *const cty::c_uint,
        data: *mut *const u8,
    ) -> bool;
}
unsafe extern "C" {
    pub fn lni2c_read_from(
        ptr: *mut ln_i2c_c,
        target: cty::c_uint,
        n: cty::c_uint,
        data: *mut u8,
    ) -> bool;
}
unsafe extern "C" {
    pub fn lni2c_begin(ptr: *mut ln_i2c_c, target: cty::c_uint) -> bool;
}
