#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const __SSP_FORTIFY_LEVEL: u32 = 0;
pub const __int20: u32 = 2;
pub const __int20__: u32 = 2;
pub type __int8_t = cty::c_schar;
pub type __uint8_t = cty::c_uchar;
pub type __int16_t = cty::c_short;
pub type __uint16_t = cty::c_ushort;
pub type __int32_t = cty::c_int;
pub type __uint32_t = cty::c_uint;
pub type __int64_t = cty::c_longlong;
pub type __uint64_t = cty::c_ulonglong;
pub type __int_least8_t = cty::c_schar;
pub type __uint_least8_t = cty::c_uchar;
pub type __int_least16_t = cty::c_short;
pub type __uint_least16_t = cty::c_ushort;
pub type __int_least32_t = cty::c_int;
pub type __uint_least32_t = cty::c_uint;
pub type __int_least64_t = cty::c_longlong;
pub type __uint_least64_t = cty::c_ulonglong;
pub type __intmax_t = cty::c_longlong;
pub type __uintmax_t = cty::c_ulonglong;
pub type __intptr_t = cty::c_int;
pub type __uintptr_t = cty::c_uint;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type int_least8_t = __int_least8_t;
pub type uint_least8_t = __uint_least8_t;
pub type int_least16_t = __int_least16_t;
pub type uint_least16_t = __uint_least16_t;
pub type int_least32_t = __int_least32_t;
pub type uint_least32_t = __uint_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = cty::c_schar;
pub type uint_fast8_t = cty::c_uchar;
pub type int_fast16_t = cty::c_short;
pub type uint_fast16_t = cty::c_ushort;
pub type int_fast32_t = cty::c_int;
pub type uint_fast32_t = cty::c_uint;
pub type int_fast64_t = cty::c_longlong;
pub type uint_fast64_t = cty::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ln_serial_tx_c {
    pub dummy: *mut cty::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ln_serial_rx_c {
    pub dummy: *mut cty::c_void,
}
pub type ln_serial_event_cb =
    ::core::option::Option<unsafe extern "C" fn(cookie: *mut cty::c_void, event: cty::c_int)>;
unsafe extern "C" {
    pub fn lnserial_tx_create(
        instance: cty::c_uint,
        dma: bool,
        buffered: bool,
    ) -> *mut ln_serial_tx_c;
}
unsafe extern "C" {
    pub fn lnserial_tx_delete(s: *mut ln_serial_tx_c);
}
unsafe extern "C" {
    pub fn lnserial_tx_init(s: *mut ln_serial_tx_c) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_tx_set_speed(s: *mut ln_serial_tx_c, speed: cty::c_uint) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_tx_transmit(
        s: *mut ln_serial_tx_c,
        size: cty::c_uint,
        buffer: *const u8,
    ) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_tx_raw_write(
        s: *mut ln_serial_tx_c,
        size: cty::c_uint,
        buffer: *const u8,
    ) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_rx_create(
        instance: cty::c_uint,
        rxBufferSize: cty::c_uint,
        dma: bool,
    ) -> *mut ln_serial_rx_c;
}
unsafe extern "C" {
    pub fn lnserial_rx_delete(s: *mut ln_serial_rx_c);
}
unsafe extern "C" {
    pub fn lnserial_rx_init(s: *mut ln_serial_rx_c) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_rx_set_speed(s: *mut ln_serial_rx_c, speed: cty::c_uint) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_rx_transmit(
        s: *mut ln_serial_rx_c,
        size: cty::c_uint,
        buffer: *const u8,
    ) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_rx_transmit_no_block(
        s: *mut ln_serial_rx_c,
        size: cty::c_uint,
        buffer: *const u8,
    ) -> cty::c_int;
}
unsafe extern "C" {
    pub fn lnserial_rx_enable_rx(s: *mut ln_serial_rx_c, enabled: bool) -> bool;
}
unsafe extern "C" {
    pub fn lnserial_rx_purge_rx(s: *mut ln_serial_rx_c);
}
unsafe extern "C" {
    pub fn lnserial_rx_read(s: *mut ln_serial_rx_c, max: cty::c_uint, to: *mut u8) -> cty::c_int;
}
unsafe extern "C" {
    pub fn lnserial_rx_set_callback(
        s: *mut ln_serial_rx_c,
        cb: ln_serial_event_cb,
        cookie: *mut cty::c_void,
    );
}
unsafe extern "C" {
    pub fn lnserial_rx_get_read_pointer(s: *mut ln_serial_rx_c, to: *mut *mut u8) -> cty::c_int;
}
unsafe extern "C" {
    pub fn lnserial_rx_consume(s: *mut ln_serial_rx_c, n: cty::c_uint);
}
