#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.72.1 */

pub use crate::pin_types::lnPin;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ln_timing_adc_c {
    pub dummy: *mut cty::c_void,
}
pub type ln_timing_adc_async_callback_t =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut cty::c_void)>;
unsafe extern "C" {
    pub fn ln_timing_adc_create(instance: cty::c_int) -> *mut ln_timing_adc_c;
    pub fn ln_timing_adc_delete(in_: *mut ln_timing_adc_c) -> bool;
    pub fn ln_timing_adc_set_source(
        instance: *mut ln_timing_adc_c,
        timer: cty::c_uint,
        channel: cty::c_uint,
        fq: cty::c_uint,
        nbPins: cty::c_uint,
        pin: *const lnPin,
    ) -> bool;
    pub fn ln_timing_adc_multi_read(
        instance: *mut ln_timing_adc_c,
        nbSamplePerChannel: cty::c_uint,
        output: *mut u16,
    ) -> bool;
    pub fn ln_timing_adc_async_read(
        instance: *mut ln_timing_adc_c,
        nbSamplePerChannel: cty::c_uint,
        output: *mut u16,
        cb: ln_timing_adc_async_callback_t,
        ctx: *mut cty::c_void,
    ) -> bool;
}
