#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.72.1 */

pub use crate::pin_types::lnPin;

pub const __SSP_FORTIFY_LEVEL: u32 = 0;
pub const __int20: u32 = 2;
pub const __int20__: u32 = 2;
pub type __int8_t = cty::c_schar;
pub type __uint8_t = cty::c_uchar;
pub type __int16_t = cty::c_short;
pub type __uint16_t = cty::c_ushort;
pub type __int32_t = cty::c_int;
pub type __uint32_t = cty::c_uint;
pub type __int64_t = cty::c_longlong;
pub type __uint64_t = cty::c_ulonglong;
pub type __int_least8_t = cty::c_schar;
pub type __uint_least8_t = cty::c_uchar;
pub type __int_least16_t = cty::c_short;
pub type __uint_least16_t = cty::c_ushort;
pub type __int_least32_t = cty::c_int;
pub type __uint_least32_t = cty::c_uint;
pub type __int_least64_t = cty::c_longlong;
pub type __uint_least64_t = cty::c_ulonglong;
pub type __intmax_t = cty::c_longlong;
pub type __uintmax_t = cty::c_ulonglong;
pub type __intptr_t = cty::c_int;
pub type __uintptr_t = cty::c_uint;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type int_least8_t = __int_least8_t;
pub type uint_least8_t = __uint_least8_t;
pub type int_least16_t = __int_least16_t;
pub type uint_least16_t = __uint_least16_t;
pub type int_least32_t = __int_least32_t;
pub type uint_least32_t = __uint_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = cty::c_schar;
pub type uint_fast8_t = cty::c_uchar;
pub type int_fast16_t = cty::c_short;
pub type uint_fast16_t = cty::c_ushort;
pub type int_fast32_t = cty::c_int;
pub type uint_fast32_t = cty::c_uint;
pub type int_fast64_t = cty::c_longlong;
pub type uint_fast64_t = cty::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ln_timing_adc_c {
    pub dummy: *mut cty::c_void,
}
pub type ln_timing_adc_async_callback_t =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut cty::c_void)>;
unsafe extern "C" {
    pub fn ln_timing_adc_create(instance: cty::c_int) -> *mut ln_timing_adc_c;
}
unsafe extern "C" {
    pub fn ln_timing_adc_delete(in_: *mut ln_timing_adc_c) -> bool;
}
unsafe extern "C" {
    pub fn ln_timing_adc_set_source(
        instance: *mut ln_timing_adc_c,
        timer: cty::c_uint,
        channel: cty::c_uint,
        fq: cty::c_uint,
        nbPins: cty::c_uint,
        pin: *const lnPin,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ln_timing_adc_multi_read(
        instance: *mut ln_timing_adc_c,
        nbSamplePerChannel: cty::c_uint,
        output: *mut u16,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ln_timing_adc_async_read(
        instance: *mut ln_timing_adc_c,
        nbSamplePerChannel: cty::c_uint,
        output: *mut u16,
        cb: ln_timing_adc_async_callback_t,
        ctx: *mut cty::c_void,
    ) -> bool;
}
