#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.72.1 */

pub type lnUsbStackEventHandler =
    ::core::option::Option<unsafe extern "C" fn(cookie: *mut cty::c_void, event: cty::c_int)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lnusb_c {
    pub dummy: *mut cty::c_void,
}
unsafe extern "C" {
    pub fn lnusb_create(instance: cty::c_uint) -> *mut lnusb_c;
    pub fn lnusb_delete(arg1: *mut lnusb_c);
    pub fn lnusb_init(
        inst: *mut lnusb_c,
        nbDescriptorLine: cty::c_int,
        deviceDescriptor: *mut *const cty::c_char,
    );
    pub fn lnusb_setConfiguration(inst: *mut lnusb_c);
    pub fn lnusb_setEventHandler(
        inst: *mut lnusb_c,
        cookie: *const cty::c_void,
        ev: lnUsbStackEventHandler,
    );
    pub fn lnusb_start(inst: *mut lnusb_c);
    pub fn lnusb_stop(inst: *mut lnusb_c);
}
