macro(LN_MERGE_LIBS)
  # ---
  if(NOT "${LN_ALREADY_MERGED}" STREQUAL "DONE")
    set(merged_name esprit_single_lib)
    set(libs_to_merge "${USED_LIBS}")
    message(STATUS "Preparing single lib ==> ${merged_name}")
    set(LN_ALREADY_MERGED
        "DONE"
        CACHE INTERNAL "")
    list(APPEND libs_to_merge ${ARGN})
    set(libs_to_keep esprit_lib)
    list(APPEND libs_to_merge ln_utils embeddedPrintf esprit_lib ${USED_LIBS})
    message(STATUS "Merging libs <${libs_to_merge}>")
    if(NOT LN_EXTERNAL_FREERTOS)
      list(APPEND libs_to_merge FreeRTOS)
    endif()
    if(LN_ENABLE_RUST)
      target_include_directories(esprit_dev INTERFACE lnarduino_c_bindings)
      list(APPEND libs_to_merge lnarduino_c_bindings)
    endif()
    foreach(lib ${libs_to_merge})
      list(APPEND objs $<TARGET_OBJECTS:${lib}>)
    endforeach()
    add_library(${merged_name} STATIC ${objs} ${ESPRIT_ROOT}/src/dummy.cpp)
    add_dependencies(${merged_name} ${libs_to_merge})
    add_custom_target(force_${merged_name} ALL DEPENDS ${merged_name})
    install(TARGETS ${merged_name} DESTINATION lib)
    # foreach(lib ${libs_to_merge}) target_add_dependencies( ${merged_name} PRIVATE ${lib}) endforeach()
  endif()
  # ---
endmacro()
