if(NOT DEFINED CORROSION_SET)
  if(LN_ARCH STREQUAL "ARM")
    if("${LN_MCU}" STREQUAL "M4")
      set(Rust_CARGO_TARGET "thumbv7em-none-eabihf")
    else()
      set(Rust_CARGO_TARGET "thumbv7m-none-eabi")
    endif()
  elseif(LN_ARCH STREQUAL "RISCV")
    set(Rust_CARGO_TARGET "riscv32imac-unknown-none-elf")
  endif()
  find_package(Corrosion REQUIRED)
  set(CORROSION_SET
      True
      CACHE INTERNAL "")
endif(NOT DEFINED CORROSION_SET)
