#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lnfast_event_group_c {
    pub dummy: *mut cty::c_void,
}
unsafe extern "C" {
    pub fn lnfast_event_group_create() -> *mut lnfast_event_group_c;
    pub fn lnfast_event_group_delete(arg1: *const lnfast_event_group_c);
    pub fn lnfast_event_group_takeOwnership(inst: *const lnfast_event_group_c);
    pub fn lnfast_event_group_set_events(inst: *const lnfast_event_group_c, event: cty::c_uint);
    pub fn lnfast_event_group_wait_events(
        inst: *const lnfast_event_group_c,
        mask: cty::c_uint,
        timeout: i32,
    ) -> cty::c_uint;
    pub fn lnfast_event_group_read_events(
        inst: *const lnfast_event_group_c,
        mask: cty::c_uint,
    ) -> cty::c_uint;
}
