[package]
name = "ws2812b"
version = "0.1.0"
edition = "2024"

[dependencies]
rs_gpio_bluepill = { path = "../../bluepill/rs_gpio_bluepill", optional = true }
rs_timer_bluepill = { path = "../../bluepill/rs_timer_bluepill", optional = true }

[features]
default = ["bluepill"]
bluepill = [
    "dep:rs_gpio_bluepill",
    "dep:rs_timer_bluepill",
]
bluepill48 = ["bluepill", "rs_timer_bluepill?/bluepill48"]
bluepill64 = ["bluepill", "rs_timer_bluepill?/bluepill64"]
